services:
  db:
    image: postgres
    restart: on-failure
    env_file:
      - .env
    container_name: sail_buddy_postgres
    volumes:
      - data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - my_network

  server:
    depends_on:
      - db
    build:
      context: ./backend/
      dockerfile: backend.Dockerfile
      target: ${TARGET}
    container_name: sail_buddy_backend
    env_file:
      - .env
    ports:
      - '8080:8080'
    networks:
      - my_network

  frontend:
    build:
      context: ./frontend/
      dockerfile: frontend.Dockerfile
      target: ${TARGET}
    container_name: sail_buddy_frontend
    env_file:
      - .env
    ports:
      - '3000:8081'
    networks:
      - my_network

volumes:
  data:

networks:
  my_network: